# Generated by Django 5.1.7 on 2025-03-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
                ('view_count', models.IntegerField()),
            ],
        ),
    ]
