# Generated by Django 3.0.6 on 2020-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='example.Student'),
        ),
    ]
