# Generated by Django 3.0.6 on 2020-05-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20200516_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
