# Generated by Django 3.0.5 on 2020-04-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='minor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_students', to='example.Subject'),
        ),
    ]
